### PR TITLE
 deleting a wishlist

### PR DESCRIPTION
**Pull request by kartik0649**

### CODE REVIEW

**Comment by Litou-lyh** [comment]
In test_wishlist.py:

image

I don't get it why you are mocking a missing wishlist like this. The id of the wishlist is automatically set, and is not None.

Maybe you want to set the id manually, and try to access with a wrong id. That will make the not found test.

**Comment by Litou-lyh** [comment]
## Still not passing the tests, but it's very close:

## In routes.py:
image

1. We actually use string(uuid) for id, so remove "int"
2. You haven't implement the bad path in this function, so it should be
```
if wishlist:
    ...
   return 204
else:
   ...
   return 404
```

## In test_routes.py:
image

1. Indentation problem here
2. Should use `assertRaises()`, see `test_update_wishlist_failed()` below as a template

**Comment by kartik0649** [comment]
ok , will fix this

**Comment by Litou-lyh** [comment]
All tests passed. Merged.

**Pull request merged**
